#!/home/rji/Documentos/PythonWork/Arduino/QuP/bin/python
# To read the sequence generated by another program
import struct


def readSeq(filename="Sequence.txt"):
    count = 0
    seq = []

    with open(filename) as fp:
        for line in fp:

            if count > 0:
                y = line.split()
                seq.append(y)

            count += 1

    return count, seq


# print('Iterating...')
def packSequence(filename="Sequence.txt"):

    cnt, Seq = readSeq(filename)
    # print(Seq)
    length = len(Seq)
    i = 0
    j = 0

    MAX_PACKET_SIZE = (cnt-1)*3
    txBuff = [' ' for ind in range(MAX_PACKET_SIZE)]

    # Iterating using while loop
    while i < length:
        e = [int(c) for c in Seq[i]]
        for k in e:
            val_byte = struct.pack('B', k)
            txBuff[j] = val_byte
            j += 1
        i += 1

    print('Cnt of Seq: ', i)
    print('Cnt of bytes: ', j)
    # print(txBuff)
    return txBuff
